export interface MaterialItem {
  id: number;
  value: string;
  label: string;
}

export interface MaterialGroup {
  sNo: string;
  category: string;
  items: MaterialItem[];
}

export const MATERIAL_GROUPS: MaterialGroup[] = [
  {
    "sNo": "A1",
    "category": "FLOORING",
    "items": [
      {
        "id": 1,
        "value": "A1_FLOORING_VITRIFIED_TILES_PLAIN_DESIGNER_AND_TACTILE",
        "label": "VITRIFIED TILES (PLAIN, DESIGNER, AND TACTILE)"
      },
      {
        "id": 2,
        "value": "A1_FLOORING_CERAMIC_PORCELAIN_TILES",
        "label": "CERAMIC / PORCELAIN TILES"
      },
      {
        "id": 3,
        "value": "A1_FLOORING_RAISED_FLOOR",
        "label": "RAISED FLOOR"
      },
      {
        "id": 4,
        "value": "A1_FLOORING_POLYURETHANE_EPOXY_COATED_FLOORING",
        "label": "POLYURETHANE / EPOXY COATED FLOORING"
      },
      {
        "id": 5,
        "value": "A1_FLOORING_CONCRETE_PAVERS_KERBS_AND_CHEQUERED_TILES_PAVING_TILES_GRASS_PAVER_PLANTABLE_BLOCKS_HOLLOW_BLOCKS_RETAINING_BLOCKS_SLOPE_STONE",
        "label": "CONCRETE PAVERS, KERBS AND CHEQUERED TILES, PAVING TILES, GRASS PAVER, PLANTABLE BLOCKS, HOLLOW BLOCKS, RETAINING BLOCKS, SLOPE STONE"
      },
      {
        "id": 6,
        "value": "A1_FLOORING_CERAMIC_OR_GLASS_MOSAIC_TILES_HANDMADE_TILE_MOSAIC_TILES",
        "label": "CERAMIC OR GLASS MOSAIC TILES / HANDMADE TILE MOSAIC TILES"
      }
    ]
  },
  {
    "sNo": "A2",
    "category": "FINISHING",
    "items": [
      {
        "id": 7,
        "value": "A2_FINISHING_PREMIX_CEMENT_PLASTER",
        "label": "PRE-MIX CEMENT PLASTER"
      },
      {
        "id": 8,
        "value": "A2_FINISHING_EMULSION_PAINTS",
        "label": "EMULSION PAINTS"
      },
      {
        "id": 9,
        "value": "A2_FINISHING_SYNTHETIC_ENAMELS",
        "label": "SYNTHETIC ENAMELS"
      },
      {
        "id": 10,
        "value": "A2_FINISHING_POLYURETHANE_PAINTS_EPOXY_PAINTS",
        "label": "POLYURETHANE PAINTS / EPOXY PAINTS"
      },
      {
        "id": 11,
        "value": "A2_FINISHING_BONDING_COAT_PRIMER_FOR_PAINT",
        "label": "BONDING COAT / PRIMER (FOR PAINT)"
      },
      {
        "id": 12,
        "value": "A2_FINISHING_TEXTURE_PAINT",
        "label": "TEXTURE PAINT"
      },
      {
        "id": 13,
        "value": "A2_FINISHING_WALL_CARE_PUTTY",
        "label": "WALL CARE PUTTY"
      },
      {
        "id": 14,
        "value": "A2_FINISHING_GLASS_FLOAT_TOUGHENED",
        "label": "GLASS (FLOAT / TOUGHENED)"
      },
      {
        "id": 15,
        "value": "A2_FINISHING_FIRE_RATED_GLASS",
        "label": "FIRE RATED GLASS"
      },
      {
        "id": 16,
        "value": "A2_FINISHING_STRUCTURAL_GLAZING_FABRICATORS",
        "label": "STRUCTURAL GLAZING FABRICATORS"
      }
    ]
  },
  {
    "sNo": "A3",
    "category": "CLADDING",
    "items": [
      {
        "id": 17,
        "value": "A3_CLADDING_GRC_PRODUCTS_GRC_SCREEN_PANELS_ETC",
        "label": "GRC PRODUCTS (GRC SCREEN, PANELS, ETC.)"
      },
      {
        "id": 18,
        "value": "A3_CLADDING_HIGH_PRESSURE_LAMINATE",
        "label": "HIGH PRESSURE LAMINATE"
      },
      {
        "id": 19,
        "value": "A3_CLADDING_ACRYLIC_SOLID_SURFACE",
        "label": "ACRYLIC SOLID SURFACE"
      }
    ]
  },
  {
    "sNo": "A4",
    "category": "FALSE CEILING",
    "items": [
      {
        "id": 20,
        "value": "A4_FALSE_CEILING_CALCIUM_SILICATE_BOARD",
        "label": "CALCIUM SILICATE BOARD"
      },
      {
        "id": 21,
        "value": "A4_FALSE_CEILING_METAL_CEILINGS",
        "label": "METAL CEILINGS"
      }
    ]
  },
  {
    "sNo": "A5",
    "category": "ADHESIVE, FILLERS, AND SEALANTS",
    "items": [
      {
        "id": 22,
        "value": "A5_ADHESIVE_FILLERS_AND_SEALANTS_ADHESIVE_FOR_TILES",
        "label": "ADHESIVE FOR TILES"
      },
      {
        "id": 23,
        "value": "A5_ADHESIVE_FILLERS_AND_SEALANTS_TILES_JOINT_FILLER_TILE_GROUTS",
        "label": "TILES JOINT FILLER, TILE GROUTS"
      },
      {
        "id": 24,
        "value": "A5_ADHESIVE_FILLERS_AND_SEALANTS_POLYSULPHIDE_SEALANT_FOR_STONE_VITRIFIED_TILE_WORKS",
        "label": "POLYSULPHIDE SEALANT (FOR STONE / VITRIFIED TILE WORKS)"
      },
      {
        "id": 25,
        "value": "A5_ADHESIVE_FILLERS_AND_SEALANTS_SILICON_SEALANTS",
        "label": "SILICON SEALANTS"
      },
      {
        "id": 26,
        "value": "A5_ADHESIVE_FILLERS_AND_SEALANTS_SILICON_WATER_REPELLENT_SOLUTION",
        "label": "SILICON WATER REPELLENT SOLUTION"
      }
    ]
  },
  {
    "sNo": "A6",
    "category": "JOINERY WOODWORK PRODUCTS",
    "items": [
      {
        "id": 27,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_PLYWOOD",
        "label": "PLYWOOD"
      },
      {
        "id": 28,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_BLOCKBOARD",
        "label": "BLOCKBOARD"
      },
      {
        "id": 29,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_LAMINATES",
        "label": "LAMINATES"
      },
      {
        "id": 30,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_DRY_PARTITION_SYSTEM",
        "label": "DRY PARTITION SYSTEM"
      },
      {
        "id": 31,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_TOILET_CUBICLES_AND_COMPACT_LAMINATED_DOORS",
        "label": "TOILET CUBICLES AND COMPACT LAMINATED DOORS"
      },
      {
        "id": 32,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_PRESSED_STEEL_DOORS_FRAME",
        "label": "PRESSED STEEL DOORS FRAME"
      },
      {
        "id": 33,
        "value": "A6_JOINERY_WOODWORK_PRODUCTS_PVC_WPC_UPVC_DOORS_AND_WINDOW_FRAME",
        "label": "PVC / WPC / UPVC DOORS AND WINDOW / FRAME"
      }
    ]
  },
  {
    "sNo": "A7",
    "category": "FIRE RATED DOORS, FIRE RATED GLASS",
    "items": [
      {
        "id": 34,
        "value": "A7_FIRE_RATED_DOORS_FIRE_RATED_GLASS_FIRE_DOOR_TESTED_AS_PER_BIS_BS_STANDARD",
        "label": "FIRE DOOR (TESTED AS PER BIS / BS STANDARD)"
      },
      {
        "id": 35,
        "value": "A7_FIRE_RATED_DOORS_FIRE_RATED_GLASS_FIRE_DOOR_TESTED_AS_PER_NFPA_STANDARD",
        "label": "FIRE DOOR (TESTED AS PER NFPA STANDARD)"
      }
    ]
  },
  {
    "sNo": "A8",
    "category": "PLUMBING",
    "items": [
      {
        "id": 36,
        "value": "A8_PLUMBING_SANITARYWARE",
        "label": "SANITARYWARE"
      },
      {
        "id": 37,
        "value": "A8_PLUMBING_SANITARY_AND_BATH_FITTINGS",
        "label": "SANITARY AND BATH FITTINGS"
      }
    ]
  },
  {
    "sNo": "A9",
    "category": "HARDWARE",
    "items": [
      {
        "id": 38,
        "value": "A9_HARDWARE_FRAMELESS_GLASS_PARTITION_FIXTURES",
        "label": "FRAMELESS GLASS PARTITION FIXTURES"
      },
      {
        "id": 39,
        "value": "A9_HARDWARE_SPIDER_FITTING_PATCH_FITTINGS",
        "label": "SPIDER FITTING / PATCH FITTINGS"
      },
      {
        "id": 40,
        "value": "A9_HARDWARE_ANCHOR_FASTENERS_FOR_FINISHING_WORKS",
        "label": "ANCHOR FASTENERS (FOR FINISHING WORKS)"
      },
      {
        "id": 41,
        "value": "A9_HARDWARE_STONE_CLADDING_CLAMPS",
        "label": "STONE CLADDING CLAMPS"
      },
      {
        "id": 42,
        "value": "A9_HARDWARE_DOOR_HARDWARE_ARCHITECTURAL_PROFILES",
        "label": "DOOR HARDWARE / ARCHITECTURAL PROFILES"
      }
    ]
  },
  {
    "sNo": "A10",
    "category": "PIPES AND FITTINGS (≤ 150 MM DIA.)",
    "items": [
      {
        "id": 43,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_DUCTILE_IRON_PIPES",
        "label": "DUCTILE IRON PIPES"
      },
      {
        "id": 44,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_CAST_IRON_PIPES_SS_PIPES_AND_FITTINGS_IS_1536",
        "label": "CAST IRON PIPES, SS PIPES, AND FITTINGS (IS 1536)"
      },
      {
        "id": 45,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_GI_AND_MS_PIPES_IS_1239_PARTI_AND_II_IS_3589",
        "label": "GI AND MS PIPES (IS 1239 PART-I & II, IS 3589)"
      },
      {
        "id": 46,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_GI_FITTINGS_MALLEABLE_IS_1879_PART_I_TO_X",
        "label": "GI FITTINGS - MALLEABLE (IS 1879 PART I TO X)"
      },
      {
        "id": 47,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_UPVC_PIPES_AND_FITTINGS_IS_4985_1981",
        "label": "UPVC PIPES AND FITTINGS (IS 4985 : 1981)"
      },
      {
        "id": 48,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_CPVC_PIPES_AND_FITTINGS_IS_15778_2007",
        "label": "CPVC PIPES AND FITTINGS (IS 15778 : 2007)"
      },
      {
        "id": 49,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_STONEWARE_PIPES_AND_GULLY_TRAPS_IS_651",
        "label": "STONEWARE PIPES AND GULLY TRAPS (IS 651)"
      },
      {
        "id": 50,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_RCC_PIPES_IS_458",
        "label": "RCC PIPES (IS 458)"
      },
      {
        "id": 51,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_COPPER_PIPES_AND_FITTINGS",
        "label": "COPPER PIPES AND FITTINGS"
      },
      {
        "id": 52,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_HIGHDENSITY_POLYETHYLENE_HDPE_PIPES_AND_FITTINGS",
        "label": "HIGH-DENSITY POLYETHYLENE (HDPE) PIPES AND FITTINGS"
      },
      {
        "id": 53,
        "value": "A10_PIPES_AND_FITTINGS_150_MM_DIA_PPR_PIPES_AND_FITTINGS",
        "label": "PPR PIPES AND FITTINGS"
      }
    ]
  },
  {
    "sNo": "A11",
    "category": "WATERPROOFING / REPELLENTS COMPOUND",
    "items": [
      {
        "id": 54,
        "value": "A11_WATERPROOFING_REPELLENTS_COMPOUND_MODIFIED_BITUMINOUS_MEMBRANE_ROOF_WATERPROOFING",
        "label": "MODIFIED BITUMINOUS MEMBRANE ROOF WATERPROOFING"
      }
    ]
  },
  {
    "sNo": "A12",
    "category": "METAL AND ROOFING",
    "items": [
      {
        "id": 55,
        "value": "A12_METAL_AND_ROOFING_ALUMINIUM_SECTION",
        "label": "ALUMINIUM SECTION"
      },
      {
        "id": 56,
        "value": "A12_METAL_AND_ROOFING_MS_HOLLOW_SECTION_PIPES",
        "label": "MS HOLLOW SECTION PIPES"
      },
      {
        "id": 57,
        "value": "A12_METAL_AND_ROOFING_MS_TUBES_SECTIONS",
        "label": "MS TUBES / SECTIONS"
      },
      {
        "id": 58,
        "value": "A12_METAL_AND_ROOFING_PREFABRICATED_SS_WORKS_SS_WORKS",
        "label": "PREFABRICATED SS WORKS / SS WORKS"
      },
      {
        "id": 59,
        "value": "A12_METAL_AND_ROOFING_METAL_ROOFS_SYSTEM",
        "label": "METAL ROOFS SYSTEM"
      },
      {
        "id": 60,
        "value": "A12_METAL_AND_ROOFING_POLYCARBONATE_SHEETS",
        "label": "POLYCARBONATE SHEETS"
      },
      {
        "id": 61,
        "value": "A12_METAL_AND_ROOFING_TENSILE_FABRIC",
        "label": "TENSILE FABRIC"
      }
    ]
  }
];

export const CIVIL_MATERIALS: MaterialItem[] = [
  { id: 50, value: "C1_CEMENT", label: "C1 \u2013 CEMENT" },
  { id: 51, value: "C2_REINFORCEMENT_BARS", label: "C2 \u2013 REINFORCEMENT BARS" },
  { id: 52, value: "C3_EPOXY_GROUT", label: "C3 \u2013 EPOXY GROUT" },
  { id: 53, value: "C4A_EXPANSION_JOINTS_FOR_VIADUCT", label: "C4(A) \u2013 EXPANSION JOINTS FOR VIADUCT" },
  { id: 54, value: "C4B_EXPANSION_JOINTS_FOR_BUILDINGS", label: "C4(B) \u2013 EXPANSION JOINTS FOR BUILDINGS" },
  { id: 55, value: "C5_ADMIXTURES", label: "C5 \u2013 ADMIXTURES" },
  { id: 56, value: "C6A_LOW_STRAIN_PILE_INTEGRITY_TESTING_UPV_TEST_REBOUND_HAMMER_TEST", label: "C6(A) \u2013 LOW STRAIN PILE INTEGRITY TESTING, UPV TEST, REBOUND HAMMER TEST" },
  { id: 57, value: "C6B_CROSSHOLE_TESTING_OF_PILES", label: "C6(B) \u2013 CROSS-HOLE TESTING OF PILES" },
  { id: 58, value: "C7_ANCHOR_FASTENERS_FOR_STRUCTURAL_WORKS", label: "C7 \u2013 ANCHOR FASTENERS (FOR STRUCTURAL WORKS)" },
  { id: 59, value: "C8_STRUCTURAL_STEEL_FABRICATION", label: "C8 \u2013 STRUCTURAL STEEL (FABRICATION)" },
  { id: 60, value: "C9_PRESTRESSING_STRAND_LRPC", label: "C9 \u2013 PRE-STRESSING STRAND (LRPC)" },
  { id: 61, value: "C10A_POTPTFE_BEARINGS", label: "C10(A) \u2013 POT/PTFE BEARINGS" },
  { id: 62, value: "C10B_ELASTOMERIC_BEARINGS", label: "C10(B) \u2013 ELASTOMERIC BEARINGS" },
  { id: 63, value: "C10C_SPHERICAL_BEARINGS", label: "C10(C) \u2013 SPHERICAL BEARINGS" },
  { id: 64, value: "C11_HORIZONTAL_TIE_BARS_SHEAR_BARS", label: "C11 \u2013 HORIZONTAL TIE BARS / SHEAR BARS" },
  { id: 65, value: "C12_HIGHDENSITY_POLYETHYLENE_HDPE_SHEATHING_FOR_PRESTRESSING_WORKS", label: "C12 \u2013 HIGH-DENSITY POLYETHYLENE (HDPE) SHEATHING (FOR PRESTRESSING WORKS)" },
  { id: 66, value: "C13_FORMWORK_RELEASE_AGENT", label: "C13 \u2013 FORMWORK RELEASE AGENT" },
  { id: 67, value: "C14_PRESTRESSING_SYSTEM", label: "C14 \u2013 PRESTRESSING SYSTEM" },
  { id: 68, value: "C15_REINFORCEMENT_COUPLERS_COLD_FORGED_PARALLEL_THREADED_TYPE", label: "C15 \u2013 REINFORCEMENT COUPLERS (COLD FORGED PARALLEL THREADED TYPE)" },
  { id: 69, value: "C16_HOLLOW_SECTIONS_TUBES", label: "C16 \u2013 HOLLOW SECTIONS, TUBES" },
  { id: 70, value: "C17_DRAINAGE_PIPES_150_MM_DIA", label: "C17 \u2013 DRAINAGE PIPES (> 150 MM DIA.)" },
  { id: 71, value: "C18_NONSHRINK_GROUT", label: "C18 \u2013 NON-SHRINK GROUT" },
  { id: 72, value: "C19_EPOXY_BONDING_AGENT_FOR_CONSTRUCTION_JOINT", label: "C19 \u2013 EPOXY BONDING AGENT (FOR CONSTRUCTION JOINT)" },
  { id: 73, value: "C20_POLYSULPHIDE_SEALANT_FOR_STRUCTURAL_WORKS", label: "C20 \u2013 POLYSULPHIDE SEALANT (FOR STRUCTURAL WORKS)" },
  { id: 74, value: "C21_STEEL_STRUCTURAL_FASTENERS", label: "C21 \u2013 STEEL STRUCTURAL FASTENERS" },
  { id: 75, value: "C22_CORROSION_PROTECTION_PAINTS", label: "C22 \u2013 CORROSION PROTECTION PAINTS" },
  { id: 76, value: "C23_MICROSILICA_ULTRAFINE_GROUND_GRANULATED_BLAST_FURNACE_SLAG_UGGBS_CONFORMING_TO_IS_167152018", label: "C23 \u2013 MICROSILICA / ULTRA-FINE GROUND GRANULATED BLAST FURNACE SLAG (UGGBS) (CONFORMING TO IS 16715:2018)" },
  { id: 77, value: "C24_FIRE_RESISTANT_PAINT", label: "C24 \u2013 FIRE RESISTANT PAINT" },
  { id: 78, value: "C25_INTEGRAL_CRYSTALLINE_WATERPROOFING", label: "C25 \u2013 INTEGRAL CRYSTALLINE WATERPROOFING" },
  { id: 79, value: "C26_WATER_STOPPER_BAR", label: "C26 \u2013 WATER STOPPER / BAR" },
  { id: 80, value: "C27_LIQUID_POLYMER_MEMBRANE_WATERPROOFING", label: "C27 \u2013 LIQUID POLYMER MEMBRANE WATERPROOFING" },
  { id: 81, value: "C28_CURING_COMPOUND", label: "C28 \u2013 CURING COMPOUND" },
  { id: 82, value: "C30_FLY_ASH_GROUND_GRANULATED_BLAST_FURNACE_SLAG_GGBS_CONFORMING_TO_IS_167142018", label: "C30 \u2013 FLY ASH / GROUND GRANULATED BLAST FURNACE SLAG (GGBS) (CONFORMING TO IS 16714:2018)" },
  { id: 83, value: "C31_PRECOATED_PROFILED_METAL_SHEETING", label: "C31 \u2013 PRE-COATED PROFILED METAL SHEETING" },
  { id: 84, value: "C32_SODIUM_SILICATE_FOR_GROUTING_PURPOSES_DURING_TBM_OPERATIONS", label: "C32 \u2013 SODIUM SILICATE (FOR GROUTING PURPOSES DURING TBM OPERATIONS)" },
  { id: 85, value: "C33_AAC_BLOCK", label: "C33 \u2013 AAC BLOCK" },
  { id: 86, value: "C34_TUNNEL_SEGMENT_EPDM", label: "C34 \u2013 TUNNEL SEGMENT EPDM" },
  { id: 87, value: "C35_ROCK_BOLTS_SWELLEX_BOLTS", label: "C35 \u2013 ROCK BOLTS / SWELLEX BOLTS" },
  { id: 88, value: "C36_GLASS_FIBER_REINFORCED_POLYMER_GFRP_BARS_CONFORMING_TO_IS_182552023_IS_182562023_AND_IRC1372022", label: "C36 \u2013 GLASS FIBER REINFORCED POLYMER (GFRP) BARS (CONFORMING TO IS 18255:2023, IS 18256:2023, AND IRC:137-2022)" },
  { id: 89, value: "C37_MATERIAL_TESTING", label: "C37 \u2013 MATERIAL TESTING" },
  { id: 90, value: "C38_RAINWATER_HARVESTING", label: "C38 \u2013 RAINWATER HARVESTING" },
  { id: 91, value: "C39_GEOTECHNICAL_INVESTIGATION", label: "C39 \u2013 GEOTECHNICAL INVESTIGATION" },
  { id: 92, value: "C40_PREMIX_PRESTRESS_CABLE_GROUTS", label: "C40 \u2013 PREMIX PRESTRESS CABLE GROUTS" },
  { id: 93, value: "C41_ULTRASONIC_LOGGING_TUBES", label: "C41 \u2013 ULTRASONIC LOGGING TUBES" },
  { id: 94, value: "C42_WELDING_ELECTRODES", label: "C42 \u2013 WELDING ELECTRODES" },
  { id: 95, value: "C43_ULTRAFINE_FLY_ASH", label: "C43 \u2013 ULTRAFINE FLY ASH" },
  { id: 96, value: "C44_DRILLING_POLYMER", label: "C44 \u2013 DRILLING POLYMER" },
  { id: 97, value: "C45_ANTICARBONATION_COATING_OF_RCC_STRUCTURES", label: "C45 \u2013 ANTI-CARBONATION COATING OF RCC STRUCTURES" },
];

export const ELECTRICAL_MATERIALS: MaterialItem[] = [
  { id: 1, value: "E1_33_KV_SINGLE_CORE_ALUMINIUMANDCOPPER_CONDUCTOR_PVC_SHEATHED_XLPE_INSULATED_300AND400_SQMM_POWER_C", label: "E1 – 33 KV, SINGLE CORE, ALUMINIUM/COPPER CONDUCTOR, PVC SHEATHED, XLPE INSULATED, 300/400 SQMM POWER CABLES" },
  { id: 2, value: "E2_25_KV_SINGLE_CORE_ALUMINIUMANDCOPPER_CONDUCTOR_PVC_SHEATHED_XLPE_INSULATED_240AND400_SQMM_POWER_C", label: "E2 – 25 KV, SINGLE CORE, ALUMINIUM/COPPER CONDUCTOR, PVC SHEATHED, XLPE INSULATED, 240/400 SQMM POWER CABLES" },
  { id: 3, value: "E3_33_KV_RETURN_CABLE_ALUMINIUM_CONDUCTOR_PVC_SHEATHED_XLPE_INSULATED_400_SQMM_RETURN_CABLE", label: "E3 – 3.3 KV RETURN CABLE ALUMINIUM CONDUCTOR, PVC SHEATHED, XLPE INSULATED, 400 SQMM RETURN CABLE" },
  { id: 4, value: "E4_33_KV_STJ_AND_CABLE_TERMINATIONS", label: "E4 – 33 KV STJ / CABLE TERMINATIONS" },
  { id: 5, value: "E5_25_KV_STJ_AND_CABLE_TERMINATIONS", label: "E5 – 25 KV STJ / CABLE TERMINATIONS" },
  { id: 6, value: "E6_33_KV_STJ_AND_CABLE_TERMINATIONS", label: "E6 – 3.3 KV STJ / CABLE TERMINATIONS" },
  { id: 7, value: "E7_LA_COMPOSITE_INSULATION_FOR_33_KV_PANEL", label: "E7 – LA (COMPOSITE INSULATION) FOR 33 KV PANEL" },
  { id: 8, value: "E8_LA_COMPOSITE_INSULATION_FOR_25_KV_SYSTEM", label: "E8 – LA (COMPOSITE INSULATION) FOR 25 KV SYSTEM" },
  { id: 9, value: "E9_33_KV_DRY_CAST_RESIN_INDUCTIVE_PT", label: "E9 – 33 KV, DRY CAST RESIN INDUCTIVE PT" },
  { id: 10, value: "E10_33_KV_DRY_CAST_RESIN_INDUCTIVE_CT", label: "E10 – 33 KV, DRY CAST RESIN INDUCTIVE CT" },
  { id: 11, value: "E11_33KVAND415V_200KVA3150KVA_DRY_CAST_RESIN_AUXILIARY_TRANSFORMERS", label: "E11 – 33KV/415V, 200KVA–3150KVA, DRY CAST RESIN AUXILIARY TRANSFORMERS" },
  { id: 12, value: "E12_33_KV_HT_PANEL_WITH_VACUUM_CIRCUIT_BREAKER_AND_ASSOCIATED_PROTECTION_SYSTEM", label: "E12 – 33 KV HT PANEL WITH VACUUM CIRCUIT BREAKER AND ASSOCIATED PROTECTION SYSTEM" },
  { id: 13, value: "E13_FLOAT_CUM_BOOST_BATTERY_CHARGER_VDC_110V", label: "E13 – FLOAT CUM BOOST BATTERY CHARGER (VDC = 110V)" },
  { id: 14, value: "E14_NI_CD_BATTERY_BANK", label: "E14 – NI CD BATTERY BANK" },
  { id: 15, value: "E15_25KV_PTFE_TYPE_SHORT_NEUTRAL_SECTION", label: "E15 – 25KV PTFE TYPE SHORT NEUTRAL SECTION" },
  { id: 16, value: "E16_107AND150_SQMM_CONTACT_WIRE_CUAG_AND_CU_ETP", label: "E16 – 107/150 SQMM CONTACT WIRE (CU-AG / CU ETP)" },
  { id: 17, value: "E17_65AND120_SQMM_MESSENGER_WIRE_CUMG_AND_CUCD", label: "E17 – 65/120 SQMM MESSENGER WIRE (CU-MG / CU-CD)" },
  { id: 18, value: "E18_933_SQMM_ACSR_AND_240_SQMM_AAC_FOR_RC_OPC_AND_BEC", label: "E18 – 93.3 SQMM ACSR / 240 SQMM AAC FOR RC, OPC AND BEC" },
  { id: 19, value: "E19_SECTION_INSULATORS_IN_DEPOT", label: "E19 – SECTION INSULATORS IN DEPOT" },
  { id: 20, value: "E20_MS_CANTILEVER_FOR_TRAMWAY_TYPE_25KV_OHE", label: "E20 – MS CANTILEVER FOR TRAMWAY TYPE 25KV OHE" },
  { id: 21, value: "E21_MODULAR_TYPE_25KV_ALUMINIUM_CANTILEVER_FOR_MAIN_LINE", label: "E21 – MODULAR TYPE 25KV ALUMINIUM CANTILEVER FOR MAIN LINE" },
  { id: 22, value: "E22_MAST_AND_FITTINGS_FOR_25KV_OHE", label: "E22 – MAST & FITTINGS FOR 25KV OHE" },
  { id: 23, value: "E23_REMOTE_TERMINAL_UNITS_RAM_256MB", label: "E23 – REMOTE TERMINAL UNITS (RAM 256MB)" },
  { id: 24, value: "E24_33_KV_GIS_PANEL", label: "E24 – 33 KV GIS PANEL" },
  { id: 25, value: "E25_25_KV_DRY_CAST_RESIN_INDUCTIVE_PT", label: "E25 – 25 KV, DRY CAST RESIN INDUCTIVE PT" },
  { id: 26, value: "E26_25_KV_DRY_CAST_RESIN_INDUCTIVE_CT", label: "E26 – 25 KV, DRY CAST RESIN INDUCTIVE CT" },
  { id: 27, value: "E27_25_KV_ISOLATORS_MOTORISEDANDMANUAL_WITH_COMPOSITE_INSULATORS_OF_1600_MM_CREEPAGE", label: "E27 – 25 KV ISOLATORS MOTORISED/MANUAL WITH COMPOSITE INSULATORS OF 1600 MM CREEPAGE" },
  { id: 28, value: "E28_25_KV_MAGNETIC_ACTUATED_AND_MECHANICAL_ACTUATED_POLE_MOUNTED_CBANDBM", label: "E28 – 25 KV MAGNETIC ACTUATED / MECHANICAL ACTUATED POLE MOUNTED CB/BM" },
  { id: 29, value: "E29_25_KV_1600_MM_CD_COMPOSITE_POST_INSULATOR", label: "E29 – 25 KV, 1600 MM CD COMPOSITE POST INSULATOR" },
  { id: 30, value: "E30_25_KV_1600_MM_CD_COMPOSITE_OPERATING_ROD_INSULATOR", label: "E30 – 25 KV, 1600 MM CD COMPOSITE OPERATING ROD INSULATOR" },
  { id: 31, value: "E31_25_KV_1600_MM_MINIMUM_CD_COMPOSITE_BRACKET_AND_STAY_INSULATORS_FOR_ALUMINIUM_CANTILEVERS", label: "E31 – 25 KV, 1600 MM MINIMUM CD COMPOSITE BRACKET AND STAY INSULATORS FOR ALUMINIUM CANTILEVERS" },
  { id: 32, value: "E32_220_AND_132_AND_66_KV_EHV_POWER_CABLE", label: "E32 – 220 / 132 / 66 KV EHV POWER CABLE" },
  { id: 33, value: "E33_220_AND_132_AND_66_KV_EHV_POWER_CABLE_TERMINATION_AND_STRAIGHT_THROUGH_JOINT", label: "E33 – 220 / 132 / 66 KV EHV POWER CABLE TERMINATION & STRAIGHT THROUGH JOINT" },
  { id: 34, value: "E34_66_KV_GAS_INSULATED_SWITCHGEAR_GIS", label: "E34 – 66 KV GAS INSULATED SWITCHGEAR (GIS)" },
  { id: 35, value: "E35_25_KV_GAS_INSULATED_SWITCHGEAR_GIS", label: "E35 – 25 KV GAS INSULATED SWITCHGEAR (GIS)" },
  { id: 36, value: "E36_220_AND_132_AND_66_KV_ANDAND_33_KV_AUXILIARY_MAINS_TRANSFORMER_AT", label: "E36 – 220 / 132 / 66 KV // 33 KV AUXILIARY MAINS TRANSFORMER (AT)" },
  { id: 37, value: "E37_220_AND_132_AND_66_KV_ANDAND_275_KV_TRACTION_TRANSFORMER_TT", label: "E37 – 220 / 132 / 66 KV // 27.5 KV TRACTION TRANSFORMER (TT)" },
  { id: 38, value: "E38_220_KV_CURRENT_TRANSFORMER_CT", label: "E38 – 220 KV CURRENT TRANSFORMER (CT)" },
  { id: 39, value: "E39_132_KV_CURRENT_TRANSFORMER_CT", label: "E39 – 132 KV CURRENT TRANSFORMER (CT)" },
  { id: 40, value: "E40_66_KV_CURRENT_TRANSFORMER_CT", label: "E40 – 66 KV CURRENT TRANSFORMER (CT)" },
  { id: 41, value: "E41_220_KV_CAPACITIVE_VOLTAGE_TRANSFORMER_CVT", label: "E41 – 220 KV CAPACITIVE VOLTAGE TRANSFORMER (CVT)" },
  { id: 42, value: "E42_132_KV_CAPACITIVE_VOLTAGE_TRANSFORMER_CVT", label: "E42 – 132 KV CAPACITIVE VOLTAGE TRANSFORMER (CVT)" },
  { id: 43, value: "E43_66_KV_CAPACITIVE_VOLTAGE_TRANSFORMER_CVT", label: "E43 – 66 KV CAPACITIVE VOLTAGE TRANSFORMER (CVT)" },
  { id: 44, value: "E44_220_KV_LIGHTNING_ARRESTORS_COMPOSITE_TYPE", label: "E44 – 220 KV LIGHTNING ARRESTORS (COMPOSITE TYPE)" },
  { id: 45, value: "E45_132_KV_LIGHTNING_ARRESTORS_COMPOSITE_TYPE", label: "E45 – 132 KV LIGHTNING ARRESTORS (COMPOSITE TYPE)" },
  { id: 46, value: "E46_66_KV_LIGHTNING_ARRESTORS_COMPOSITE_TYPE", label: "E46 – 66 KV LIGHTNING ARRESTORS (COMPOSITE TYPE)" },
  { id: 47, value: "E47_220_KV_CIRCUIT_BREAKER_CB", label: "E47 – 220 KV CIRCUIT BREAKER (CB)" },
  { id: 48, value: "E48_132_KV_CIRCUIT_BREAKER_CB", label: "E48 – 132 KV CIRCUIT BREAKER (CB)" },
  { id: 49, value: "E49_66_KV_CIRCUIT_BREAKER_CB", label: "E49 – 66 KV CIRCUIT BREAKER (CB)" },
  { id: 50, value: "E50_220_AND_132_AND_66_KV_ISOLATOR", label: "E50 – 220 / 132 / 66 KV ISOLATOR" },
  { id: 51, value: "E51_RELAYS_BAY_CONTROLLER_UNIT_AND_PROTECTION_RELAY_ON_IEC_61850_PROTOCOL", label: "E51 – RELAYS (BAY CONTROLLER UNIT AND PROTECTION RELAY ON IEC 61850 PROTOCOL)" },
  { id: 52, value: "E52_SUBSTATION_AUTOMATION_SAS_ON_IEC_61850_PROTOCOL", label: "E52 – SUB-STATION AUTOMATION (SAS) ON IEC 61850 PROTOCOL" },
  { id: 53, value: "E53_NGR", label: "E53 – NGR" },
  { id: 54, value: "E54_ELECTRICAL_PANELS_AND_DISTRIBUTION_BOARDS", label: "E54 – ELECTRICAL PANELS / DISTRIBUTION BOARDS" },
  { id: 55, value: "E55_FIRE_FIGHTING_PUMPS_FIRE_SERVICES", label: "E55 – FIRE FIGHTING PUMPS (FIRE SERVICES)" },
  { id: 56, value: "E56_ADDRESSABLE_FIRE_DETECTION_SYSTEM", label: "E56 – ADDRESSABLE FIRE DETECTION SYSTEM" },
  { id: 57, value: "E57_CLEAN_AGENT_BASED_FIRE_SUPPRESSION_SYSTEM_FOR_PANELS_INERT_GAS_IG100_BASED", label: "E57 – CLEAN AGENT BASED FIRE SUPPRESSION SYSTEM FOR PANELS (INERT GAS IG-100 BASED)" },
  { id: 58, value: "E58_LT_CU_AND_AL_CABLES_FOR_UNDERGROUND_WORK", label: "E58 – LT CU AND AL CABLES FOR UNDERGROUND WORK" },
  { id: 59, value: "E59_WIRES_FOR_UNDERGROUND_WORK_AND_BMS_CONTROL_CABLES", label: "E59 – WIRES FOR UNDERGROUND WORK AND BMS CONTROL CABLES" },
  { id: 60, value: "E60_UPS_60_KVA_AND_ABOVE", label: "E60 – UPS (60 KVA AND ABOVE)" },
  { id: 61, value: "E61_BATTERY_NICD_FOR_UPS", label: "E61 – BATTERY (NICD) FOR UPS" },
  { id: 62, value: "E62_LED_LIGHT_FIXTURES_INDOOR_APPLICATION", label: "E62 – LED LIGHT FIXTURES (INDOOR APPLICATION)" },
  { id: 63, value: "E63_LED_LIGHT_FIXTURES_OUTDOOR_APPLICATION", label: "E63 – LED LIGHT FIXTURES (OUTDOOR APPLICATION)" },
  { id: 64, value: "E64_MS_AND_GI_PIPES", label: "E64 – MS & GI PIPES" },
  { id: 65, value: "E65_SEWAGE_PUMPS_SUBMERGED_SEMI_OPEN_IMPELLER_AND_SEEPAGE_PUMPS", label: "E65 – SEWAGE PUMPS SUBMERGED SEMI OPEN IMPELLER / SEEPAGE PUMPS" },
  { id: 66, value: "E66_LT_BUS_DUCT_SANDWICH_TYPE", label: "E66 – LT BUS DUCT (SANDWICH TYPE)" },
  { id: 67, value: "E67_DG_SETS", label: "E67 – DG SETS" },
  { id: 68, value: "E68_AIR_CONDITIONING_SYSTEM_VRF_AND_SPLIT", label: "E68 – AIR CONDITIONING SYSTEM (VRF & SPLIT)" },
  { id: 69, value: "E69_FRLSH_XLPE_CABLE", label: "E69 – FRLSH XLPE CABLE" },
  { id: 70, value: "E70_FRLSH_PVC_CABLES_AND_FR_WIRE", label: "E70 – FRLSH PVC CABLES / FR WIRE" },
  { id: 71, value: "E71_WATER_COOLED_SCREW_AND_CENTRIFUGAL_CHILLERS", label: "E71 – WATER COOLED SCREW / CENTRIFUGAL CHILLERS" },
  { id: 72, value: "E72_AIR_COOLED_SCREW_CHILLERS", label: "E72 – AIR COOLED SCREW CHILLERS" },
  { id: 73, value: "E73_ECS_PUMPS_VERTICAL_INLINE_AND_MONOBLOCK_AND_HORIZONTAL_SPLIT_CASE", label: "E73 – ECS PUMPS (VERTICAL INLINE / MONOBLOCK / HORIZONTAL SPLIT CASE)" },
  { id: 74, value: "E74_VARIABLE_SPEED_DISTRIBUTED_AHUS_AND_FCU_PUMPS", label: "E74 – VARIABLE SPEED DISTRIBUTED AHU’S AND FCU PUMPS" },
  { id: 75, value: "E75_ECS_FANS_AXIAL_AND_INLINE_AND_WALL_MOUNTED", label: "E75 – ECS FANS (AXIAL / INLINE / WALL MOUNTED)" },
  { id: 76, value: "E76_AIR_HANDLING_UNIT_PLUG_FANS_WITH_PERMANENT_MAGNET_MOTOR", label: "E76 – AIR HANDLING UNIT (PLUG FANS WITH PERMANENT MAGNET MOTOR)" },
  { id: 77, value: "E77_ECS_SOUND_ATTENUATOR", label: "E77 – ECS SOUND ATTENUATOR" },
  { id: 78, value: "E78_FIRE_DAMPERS_MFD_AND_FLFD_AND_FMD", label: "E78 – FIRE DAMPERS (MFD / FLFD / FMD)" },
  { id: 79, value: "E79_PREFABRICATED_DUCTS", label: "E79 – PREFABRICATED DUCTS" },
  { id: 80, value: "E80_VFD", label: "E80 – VFD" },
  { id: 81, value: "E81_PLC_BASED_BMS_FOR_BUILDING_SERVICES", label: "E81 – PLC BASED BMS FOR BUILDING SERVICES" },
  { id: 82, value: "E82_TUNNEL_VENTILATION_FAN_WITH_FIRE_RATING_OF_250C_FOR_2_HRS", label: "E82 – TUNNEL VENTILATION FAN WITH FIRE RATING OF 250°C FOR 2 HRS" },
  { id: 83, value: "E83_TVS_SOUND_ATTENUATOR_WITH_FIRE_RATING_OF_250C_FOR_2_HRS", label: "E83 – TVS SOUND ATTENUATOR WITH FIRE RATING OF 250°C FOR 2 HRS" },
  { id: 84, value: "E84_AIR_COMPRESSOR", label: "E84 – AIR COMPRESSOR" },
  { id: 85, value: "E85_TUNNEL_VENTILATION_DAMPER_WITH_FIRE_RATING_OF_250C_FOR_2_HRS", label: "E85 – TUNNEL VENTILATION DAMPER WITH FIRE RATING OF 250°C FOR 2 HRS" },
  { id: 86, value: "E86_EOT_CRANE", label: "E86 – EOT CRANE" },
  { id: 87, value: "E87_HIGH_MAST_AND_STREET_LIGHT_POLE", label: "E87 – HIGH MAST AND STREET LIGHT POLE" },
  { id: 88, value: "E88_COOLING_TOWER", label: "E88 – COOLING TOWER" },
];
